services:
  app:
    build: .
    environment:
      BACKTEST_STORE_PATH: /app/backtest-store
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data:ro
      - ./data/backtest-store:/app/backtest-store
